version: '3'

services:
  prune:
    image: ghcr.io/ledermann/docker-prune

    environment:
      # prune every 2h
      SLEEP: 7200

    volumes:
      # map docker socket into container
      - /var/run/docker.sock:/var/run/docker.sock

    deploy:
      # run on every docker node
      mode: global
